# Generated by Django 6.0.6 on 2026-06-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('portaria_id', models.CharField(max_length=50)),
                ('numero_portaria', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=255)),
                ('data_hora', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogExcluido',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero_portaria', models.CharField(max_length=100)),
                ('data_exclusao', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('data_publicacao', models.CharField(max_length=50)),
                ('data_inicio_periodo', models.CharField(db_column='dataInicioPeriodo', max_length=50)),
                ('data_fim_periodo', models.CharField(db_column='dataFimPeriodo', max_length=50)),
                ('fundamentacao', models.TextField()),
                ('objetivo', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('auditor_nome', models.CharField(max_length=255)),
                ('auditor_cargo', models.CharField(max_length=255)),
                ('auditor_matricula', models.CharField(max_length=50)),
                ('supervisor_nome', models.CharField(max_length=255)),
                ('supervisor_cargo', models.CharField(max_length=255)),
                ('supervisor_sector', models.CharField(max_length=50)),
                ('unidades_jurisdicionadas', models.JSONField(default=list)),
                ('concluido_no_prazo', models.BooleanField(default=True)),
                ('tempo_atraso_dias', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'api_portaria',
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('portaria_id', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.CharField(max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('Assessor Administrativo I', 'Assessor Administrativo I'), ('Assessor Administrativo II', 'Assessor Administrativo II'), ('Assessor Tecnico de Controle Externo', 'Assessor Tecnico de Controle Externo'), ('Auditor de Controle Externo', 'Auditor de Controle Externo')], max_length=255)),
                ('sector', models.CharField(choices=[('SEAMP', 'SEAMP'), ('SECEX', 'SECEX')], max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.CharField(max_length=50)),
                ('data_fim', models.CharField(max_length=50)),
                ('duracao_dias_uteis', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('portaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='api.portaria')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=50)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('portaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.portaria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('data_hora', models.CharField(max_length=50)),
                ('portaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.portaria')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('matricula_servidor', models.CharField(max_length=50)),
                ('nome_servidor', models.CharField(max_length=255)),
                ('cargo_servidor', models.CharField(max_length=255)),
                ('numero_portaria_ferias', models.CharField(max_length=100)),
                ('data_inicio', models.CharField(max_length=50)),
                ('data_fim', models.CharField(max_length=50)),
                ('dias', models.IntegerField()),
                ('periodo_aquisitivo', models.CharField(max_length=50)),
                ('parcela', models.CharField(max_length=50)),
                ('data_cadastro', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='api.user')),
            ],
        ),
    ]
